language: csharp
mono: none
dotnet: 1.0.1
os: osx
solution: NValidate.sln

env:
  global:
  # NUGET_API_KEY
  - secure: "h7qhjCiXZ4Z0pCK4v/8NbqosnlDrJbM0mfd0LGKnF4tVj4MVVZ9LiKdcvqq3NsHBokfCYFMd5/aqDNZYjzD+LCEnfjAS3FAxvkJvbzk5Z2eoXulrQ5kQblaYBA9yBHUWXH9TPFthVRNQWbmBcvPNJGya5TAhDqn/yX9hKKhnDL1RwSxSMrWsDC/278sBONK4ZYqjH1HwHr4Ktq7/91oHlTw21ISoR9fO6K8wLYdWE3EBH4Y6xaS6QL33uO3OMZYbnJpV6Hc5w+c0ek/fqYJx41nssHdMbBJlSHcM84/Zrl+zMSYIQkKVeyVL0gY0hdjSrnNuGFM7hF+3mecmr7D7EcHKsQ6DMlCn0mB4V9uon+UU/4NhaO/gLwxdnNh39wY+cMU2TAMaUd5Fe9acdlT3wR55olgUzpdxatG6Q4bFXMgaKiMMOB3EA0KY97fP6N40eALAumb5x6cc933HDLgqWYW0JFC6A8KSRUxDzmlRTND/0x8MjoPJs5Jfq4KG3qksweU8Y6m5nlYP3yf6JuTE/st8lras6sbVT50szl1j2qqDmqzAi5Mj1qesja9uVufWnvaIsZF4KcnYybjpzdNDnHBLFvKQqUeR+LYtLmlQE6+IwbG2zUnSlb0UizQd3BkOicJE0UQ456LSN4BSjwk0+d3CP0X571l2ruwKm7zLCHU="

install:
- ulimit -n 512
- dotnet restore

script: dotnet test test/NValidate.Tests.csproj

deploy:
- provider: script
  skip_cleanup: true
  script: ./tools/tonuget.sh ${NUGET_API_KEY}
  on:
    branch: master
    tags: false
