configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build: dotnet restore
build_script: dotnet build --configuration Release
test_script: dotnet run --configuration Release --project test\NValidate.Tests.csproj
after_test: dotnet pack src\NValidate.csproj --configuration Release

artifacts:
- path: '**\*.nupkg'
  name: NValidate

deploy:
- provider: NuGet
  api_key:
    secure: waNr/Pn+wEzJSAce/RgDCsQ1acssRNRjFr+hLDjIDTDAj/UHfmVW9Qz2JMfIeXFx
  skip_symbols: true
  artifact: NValidate
  on:
    appveyor_repo_tag: true
